### ISSUE TITLE
TypeError: 'constant' object is not callable

### ISSUE THREAD

**Issue by joe42** [joe42/CloudFusion#23]
Occurs (infrequently) with psutil version 0.5.1. 

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pymodules/python2.7/CloudFusion-7.5.19-
py2.7.egg/cloudfusion/store/store_sync_thread.py", line 209, in run
    self._run()
  File "/usr/lib/pymodules/python2.7/CloudFusion-7.5.19-
py2.7.egg/cloudfusion/store/store_sync_thread.py", line 244, in _run
    self.tidy_up()
  File "/usr/lib/pymodules/python2.7/CloudFusion-7.5.19-
py2.7.egg/cloudfusion/store/store_sync_thread.py", line 271, in tidy_up
    self._remove_sleeping_writers()
  File "/usr/lib/pymodules/python2.7/CloudFusion-7.5.19-
py2.7.egg/cloudfusion/store/store_sync_thread.py", line 125, in 
_remove_sleeping_writers
    if writer.is_sleeping():
  File "/usr/lib/pymodules/python2.7/CloudFusion-7.5.19-
py2.7.egg/cloudfusion/store/store_worker.py", line 270, in is_sleeping
    return not self.is_finished() and p.status() == 'sleeping' and not 
p.connections()
TypeError: 'constant' object is not callable
```

**Comment by joe42** [comment]
psutil version>=2.0.0 is required to run CloudFusion.
