### ISSUE TITLE
Bad address Error Starting CloudFusion with Google

### ISSUE THREAD

**Issue by kaineuk** [joe42/CloudFusion#26]
Hi there I get this when I try to mount Google drive 
root@bk:~# cloudfusion --config ~/Google.ini google
root@bk:~# Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/main.py", line 53, in set_configuration
    shutil.copyfile(config_file, virtual_configuration_file)                                File "/usr/lib/python2.7/shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
IOError: [Errno 14] Bad address

**Comment by kaineuk** [comment]
With cloudfusion --config ~/Google.ini 
google foreground

I get this 

Logging handler DBHandler was initialized before calling cloudfusion.mylogging.db_logging_thread.start(). Nothing will be logged.
Exception in write: GSResponseError: 403 Forbidden
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccountProblem</Code><Message>Your Google account is not currently enabled for this operation.  Please check https://code.google.com/apis/console/#:billing to see if you have a past due balance or if the credit card (or other payment mechanism) on your account is expired. You can find additional information at https://developers.google.com/storage/docs/signup</Message></Error>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/fuse.py", line 301, in _wrapper_
    return func(_args, *_kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/fuse.py", line 377, in write
    return self.operations('write', path, data, offset, fh)
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/fuse.py", line 512, in **call**
    return getattr(self, op)(_args)
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/pyfusebox/transparent_configurable_pyfusebox.py", line 125, in write
    return super( TransparentConfigurablePyFuseBox, self ).write(path, buf, offset, fh)
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/pyfusebox/configurable_pyfusebox.py", line 177, in write
    written_bytes = self.virtual_file.write(buf, offset)
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/pyfusebox/virtualconfigfile.py", line 50, in write
    self._initialize_store()
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/pyfusebox/virtualconfigfile.py", line 153, in _initialize_store
    store = self.__get_new_store(service, config) #catch error?
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/pyfusebox/virtualconfigfile.py", line 200, in __get_new_store
    raise e
GSResponseError: GSResponseError: 403 Forbidden
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccountProblem</Code><Message>Your Google account is not currently enabled for this operation.  Please check https://code.google.com/apis/console/#:billing to see if you have a past due balance or if the credit card (or other payment mechanism) on your account is expired. You can find additional information at https://developers.google.com/storage/docs/signup</Message></Error>
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CloudFusion-7.5.19-py2.7.egg/cloudfusion/main.py", line 53, in set_configuration
    shutil.copyfile(config_file, virtual_configuration_file)
  File "/usr/lib/python2.7/shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
IOError: [Errno 14] Bad address

**Comment by kaineuk** [comment]
I don't get the AccountProblem section iv setup the api access and the secrete key ect. Do I have to pay Google to access my gdrive this way ?
