### ISSUE TITLE
Can only run as root

### ISSUE THREAD

**Issue by marlarius** [joe42/CloudFusion#36]
Hi,

I just installed CloudFusion. Apparently it can only run as root (sudo) but then I can't access the files from my normal account. If I don't run as root, I get a permission denied. How do I run it with root?

The full output is below.

Another question: CloudFusion is painfully slow which is probably mainly caused by it running on an under-powered netbook. So I don't blame CloudFusion! If I choose to uninstall it, how do I do that? The python setup script downloaded and installed a whole bunch of libs and scripts.

Thanks,
Martin

Full output from terminal:

cloudfusion --config ~/Dropbox.ini ~/mnt
Traceback (most recent call last):
  File "/usr/local/bin/cloudfusion", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 837, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2489, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2474, in _dep_map
    for extra, reqs in split_sections(self._get_metadata(name)):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2878, in split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2174, in yield_lines
    for ss in strs:
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2503, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1477, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1469, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1580, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/google_apitools-0.5.3-py2.7.egg/EGG-INFO/requires.txt'
marlar@marlar-aspire ~ $

**Comment by ghost** [comment]
I have the same issue running elementaryOS 0.4 and CloudFusion GDrive.

I have it installed it now using sudo. Now I can't open my GDrive folder without having to run my file manager with sudo.

Is there a simple and clean solution or can I change the permissions without messing my GDrive up? :worried:
